#!/usr/bin/env bash
# worktree-spawn: create an isolated git worktree with a deterministic PORT_BASE
# so a heavy multi-port dev server can run in parallel across Claude sessions.
#
# Usage:
#   worktree-spawn.sh <branch> [--from <base-branch>] [--dir <worktree-dir>]
#   worktree-spawn.sh --list
#   worktree-spawn.sh --remove <branch>
#
# Conventions:
# - Worktrees live next to the repo at ../<repo>-worktrees/<branch>
#   (override with --dir or WORKTREE_ROOT env var).
# - PORT_BASE is allocated in 100-port blocks: main=3000, next=3100, ...
#   Registry is stored at <repo>/.worktree-ports.json (gitignored).
# - Each worktree gets a .envrc that exports PORT_BASE; the rest of the port
#   layout (FRONTEND_PORT, API_PORT, ...) is expected to live in a committed
#   .envrc.template that this script sources if present.
#
# Idempotent: re-running spawn for an existing branch prints the existing
# PORT_BASE without re-allocating.

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || true)"
if [ -z "${REPO_ROOT}" ]; then
  echo "ERROR: not inside a git repository" >&2
  exit 1
fi

REPO_NAME="$(basename "${REPO_ROOT}")"
WORKTREE_ROOT="${WORKTREE_ROOT:-$(dirname "${REPO_ROOT}")/${REPO_NAME}-worktrees}"
REGISTRY="${REPO_ROOT}/.worktree-ports.json"
PORT_BASE_START="${PORT_BASE_START:-3000}"
PORT_BASE_STEP="${PORT_BASE_STEP:-100}"

ensure_registry() {
  if [ ! -f "${REGISTRY}" ]; then
    printf '{\n  "main": %d\n}\n' "${PORT_BASE_START}" > "${REGISTRY}"
  fi
}

read_port() {
  local branch="$1"
  python3 -c "
import json, sys
try:
    d = json.load(open('${REGISTRY}'))
except Exception:
    sys.exit(1)
print(d.get('${branch}', ''))
"
}

allocate_port() {
  local branch="$1"
  python3 - "$REGISTRY" "$branch" "$PORT_BASE_STEP" "$PORT_BASE_START" <<'PY'
import json, sys
reg_path, branch, step, start = sys.argv[1], sys.argv[2], int(sys.argv[3]), int(sys.argv[4])
with open(reg_path) as f:
    d = json.load(f)
if branch in d:
    print(d[branch])
    sys.exit(0)
used = set(d.values())
p = start
while p in used:
    p += step
d[branch] = p
with open(reg_path, "w") as f:
    json.dump(d, f, indent=2, sort_keys=True)
    f.write("\n")
print(p)
PY
}

release_port() {
  local branch="$1"
  python3 - "$REGISTRY" "$branch" <<'PY'
import json, sys
reg_path, branch = sys.argv[1], sys.argv[2]
with open(reg_path) as f:
    d = json.load(f)
d.pop(branch, None)
with open(reg_path, "w") as f:
    json.dump(d, f, indent=2, sort_keys=True)
    f.write("\n")
PY
}

write_envrc() {
  local worktree_dir="$1" port_base="$2"
  local envrc="${worktree_dir}/.envrc"
  {
    echo "# Auto-generated by worktree-spawn. PORT_BASE is the offset for this worktree."
    echo "# Edit .envrc.template in the repo root to define the port layout (API_PORT, etc)."
    echo "export PORT_BASE=${port_base}"
    if [ -f "${worktree_dir}/.envrc.template" ]; then
      echo "source_env .envrc.template"
    fi
  } > "${envrc}"
}

default_base_branch() {
  for b in main master; do
    if git -C "${REPO_ROOT}" show-ref --verify --quiet "refs/heads/${b}"; then
      echo "$b"; return
    fi
  done
  git -C "${REPO_ROOT}" symbolic-ref --short HEAD 2>/dev/null || echo "HEAD"
}

cmd_spawn() {
  local branch="$1" base_branch="${2:-}" target_dir="${3:-}"
  [ -z "${base_branch}" ] && base_branch="$(default_base_branch)"
  [ -z "${target_dir}" ] && target_dir="${WORKTREE_ROOT}/${branch}"

  ensure_registry

  # If worktree already exists at target_dir, just report state and exit.
  if git -C "${REPO_ROOT}" worktree list --porcelain | grep -q "^worktree ${target_dir}\$"; then
    local existing
    existing="$(read_port "${branch}")"
    echo "Worktree already exists: ${target_dir}"
    [ -n "${existing}" ] && echo "PORT_BASE=${existing}"
    exit 0
  fi

  mkdir -p "$(dirname "${target_dir}")"

  # Create worktree. If branch exists locally, check it out; otherwise create
  # a new branch off base_branch.
  if git -C "${REPO_ROOT}" show-ref --verify --quiet "refs/heads/${branch}"; then
    git -C "${REPO_ROOT}" worktree add "${target_dir}" "${branch}"
  else
    git -C "${REPO_ROOT}" worktree add -b "${branch}" "${target_dir}" "${base_branch}"
  fi

  local port_base
  port_base="$(allocate_port "${branch}")"
  write_envrc "${target_dir}" "${port_base}"

  cat <<EOF

Worktree ready.
  path:       ${target_dir}
  branch:     ${branch}
  base:       ${base_branch}
  PORT_BASE:  ${port_base}
  envrc:      ${target_dir}/.envrc

Next steps:
  cd ${target_dir}
  direnv allow            # if you use direnv
  # ...your dev server reads PORT_BASE (or sourced .envrc.template vars)
EOF
}

cmd_list() {
  ensure_registry
  echo "Registered PORT_BASE allocations (${REGISTRY}):"
  python3 -c "
import json
with open('${REGISTRY}') as f:
    d = json.load(f)
for k, v in sorted(d.items(), key=lambda kv: kv[1]):
    print(f'  {v:>5}  {k}')
"
  echo ""
  echo "Active worktrees:"
  git -C "${REPO_ROOT}" worktree list
}

cmd_remove() {
  local branch="$1" force="${2:-}"
  local worktree_dir="${WORKTREE_ROOT}/${branch}"

  if git -C "${REPO_ROOT}" worktree list --porcelain | grep -q "^worktree ${worktree_dir}\$"; then
    if [ "${force}" = "--force" ] || [ "${force}" = "-f" ]; then
      git -C "${REPO_ROOT}" worktree remove --force "${worktree_dir}"
    else
      if ! git -C "${REPO_ROOT}" worktree remove "${worktree_dir}" 2>/dev/null; then
        echo "Worktree has uncommitted or untracked files: ${worktree_dir}" >&2
        echo "Re-run with --force to discard, or commit/push first." >&2
        return 1
      fi
    fi
    echo "Removed worktree: ${worktree_dir}"
  else
    echo "No worktree at ${worktree_dir} (skipping git worktree remove)"
  fi

  release_port "${branch}"
  echo "Released PORT_BASE for branch ${branch}"
}

case "${1:-}" in
  --list|list)
    cmd_list
    ;;
  --remove|remove|rm)
    shift
    [ -z "${1:-}" ] && { echo "Usage: worktree-spawn.sh --remove <branch> [--force]" >&2; exit 1; }
    cmd_remove "$1" "${2:-}"
    ;;
  ""|--help|-h)
    cat >&2 <<EOF
Usage:
  worktree-spawn.sh <branch> [base-branch] [target-dir]   # spawn
  worktree-spawn.sh --list                                # show registry + worktrees
  worktree-spawn.sh --remove <branch>                     # remove worktree + free port
EOF
    [ "${1:-}" = "" ] && exit 1 || exit 0
    ;;
  *)
    branch="$1"; shift
    base="${1:-}"; [ $# -gt 0 ] && shift
    dir="${1:-}"
    cmd_spawn "${branch}" "${base}" "${dir}"
    ;;
esac
